### ISSUE TITLE
Confirmation Link send on is redirecting to localhost(Failing) on production

### ISSUE THREAD

**Issue by JKirito** [tech-for-better/solent-mind#75]
### Wrong redirection on production website...

![bugs_001](https://user-images.githubusercontent.com/58296258/146182155-9031ed98-34df-4bf5-9343-a5fe003dd767.jpg)

**Comment by MJOW1999** [comment]
Hi @JKirito, thank you for your feedback! We are currently still in development, when we are ready for production we will change the base url to the correct one
